/**:
  ros__parameters:
    min_longitudinal_offset: 2.41667
    max_longitudinal_offset: 2.68921
    min_lateral_offset: -0.9000
    max_lateral_offset: 1.094165
    min_height_offset: 1.28213
    max_height_offset: 1.47338