/**:
  ros__parameters:
    wheel_radius: 0.367015 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.26477 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 3.193 # between front wheel center and rear wheel center
    wheel_tread: 1.67797 # between left wheel center and right wheel center
    front_overhang: 0.813344 # between front wheel center and vehicle front
    rear_overhang: 0.91196 # between rear wheel center and vehicle rear
    left_overhang: 0.257925 # between left wheel center and vehicle left
    right_overhang: 0.257925 # between right wheel center and vehicle right
    vehicle_height: 2.25509 # 2.25509 with RTB,1.93787 without RTB
    max_steer_angle: 0.698 # [rad] usually between 0.6109 and 0.6981 (35deg and 40deg)
